"""Send nightly email digest of local news articles."""

import os
import smtplib
from datetime import datetime, timedelta, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from dotenv import load_dotenv
from supabase import create_client

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
GMAIL_ADDRESS = os.getenv("GMAIL_ADDRESS")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")
DIGEST_RECIPIENT = os.getenv("DIGEST_RECIPIENT")


def get_supabase():
    """Create Supabase client."""
    return create_client(SUPABASE_URL, SUPABASE_KEY)


def get_recent_articles(supabase):
    """Get accessible local articles from the past 24 hours."""
    yesterday = (datetime.now(timezone.utc) - timedelta(hours=24)).isoformat()

    result = supabase.table("articles").select(
        "title, bullet, location, priority, url, published_at"
    ).eq("is_local", True).eq("is_accessible", True).gte(
        "fetched_at", yesterday
    ).order("priority", desc=True).order("published_at", desc=True).execute()

    return result.data


def format_html_email(articles):
    """Format articles as HTML email."""
    today = datetime.now().strftime("%B %d, %Y")

    priority_labels = {
        5: ("🔴", "BREAKING"),
        4: ("🟠", "IMPORTANT"),
        3: ("🟡", "LOCAL NEWS"),
        2: ("🟢", "MINOR"),
        1: ("⚪", "LOW PRIORITY"),
    }

    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; }}
            h1 {{ color: #1a1a1a; border-bottom: 2px solid #333; padding-bottom: 10px; }}
            .priority-section {{ margin: 20px 0; }}
            .priority-header {{ font-size: 14px; font-weight: bold; color: #666; margin-bottom: 10px; }}
            .article {{ background: #f9f9f9; padding: 15px; margin: 10px 0; border-radius: 8px; border-left: 4px solid #ccc; }}
            .article.p5 {{ border-left-color: #dc3545; }}
            .article.p4 {{ border-left-color: #fd7e14; }}
            .article.p3 {{ border-left-color: #ffc107; }}
            .article.p2 {{ border-left-color: #28a745; }}
            .article.p1 {{ border-left-color: #6c757d; }}
            .location {{ font-size: 12px; color: #666; margin-bottom: 5px; }}
            .title {{ font-size: 16px; font-weight: bold; margin-bottom: 8px; }}
            .title a {{ color: #1a1a1a; text-decoration: none; }}
            .title a:hover {{ text-decoration: underline; }}
            .bullet {{ font-size: 14px; color: #444; line-height: 1.5; }}
            .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #999; }}
        </style>
    </head>
    <body>
        <h1>📰 Kansas Local News Digest</h1>
        <p style="color: #666;">{today} • {len(articles)} new articles</p>
    """

    if not articles:
        html += "<p>No new articles in the past 24 hours.</p>"
    else:
        # Group by priority
        by_priority = {}
        for article in articles:
            p = article.get("priority") or 3
            if p not in by_priority:
                by_priority[p] = []
            by_priority[p].append(article)

        for priority in sorted(by_priority.keys(), reverse=True):
            emoji, label = priority_labels.get(priority, ("⚪", "OTHER"))
            html += f"""
            <div class="priority-section">
                <div class="priority-header">{emoji} {label}</div>
            """

            for article in by_priority[priority]:
                location = article.get("location") or "Kansas"
                title = article.get("title", "Untitled")
                bullet = article.get("bullet") or "No summary available."
                url = article.get("url", "#")

                html += f"""
                <div class="article p{priority}">
                    <div class="location">📍 {location}</div>
                    <div class="title"><a href="{url}">{title}</a></div>
                    <div class="bullet">{bullet}</div>
                </div>
                """

            html += "</div>"

    html += """
        <div class="footer">
            Generated by Xanadu News Aggregator
        </div>
    </body>
    </html>
    """

    return html


def format_plain_text(articles):
    """Format articles as plain text fallback."""
    today = datetime.now().strftime("%B %d, %Y")
    text = f"Kansas Local News Digest - {today}\n"
    text += f"{len(articles)} new articles\n"
    text += "=" * 50 + "\n\n"

    if not articles:
        text += "No new articles in the past 24 hours.\n"
    else:
        current_priority = None
        for article in articles:
            p = article.get("priority") or 3
            if p != current_priority:
                current_priority = p
                text += f"\n--- PRIORITY {p} ---\n\n"

            location = article.get("location") or "Kansas"
            title = article.get("title", "Untitled")
            bullet = article.get("bullet") or "No summary available."

            text += f"📍 {location}\n"
            text += f"{title}\n"
            text += f"→ {bullet}\n\n"

    return text


def send_email(html_content, plain_content, article_count):
    """Send email via Gmail SMTP."""
    if not all([GMAIL_ADDRESS, GMAIL_APP_PASSWORD, DIGEST_RECIPIENT]):
        print("Missing email configuration. Set GMAIL_ADDRESS, GMAIL_APP_PASSWORD, DIGEST_RECIPIENT.")
        return False

    today = datetime.now().strftime("%b %d, %Y")
    subject = f"📰 Kansas Local News - {today} ({article_count} articles)"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = DIGEST_RECIPIENT

    msg.attach(MIMEText(plain_content, "plain"))
    msg.attach(MIMEText(html_content, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_ADDRESS, DIGEST_RECIPIENT, msg.as_string())
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False


def main():
    """Generate and send nightly digest."""
    print("Fetching recent articles...")
    supabase = get_supabase()
    articles = get_recent_articles(supabase)
    print(f"Found {len(articles)} articles from the past 24 hours")

    if not articles:
        print("No new articles to send.")
        return

    print("Formatting email...")
    html_content = format_html_email(articles)
    plain_content = format_plain_text(articles)

    print(f"Sending digest to {DIGEST_RECIPIENT}...")
    if send_email(html_content, plain_content, len(articles)):
        print("Email sent successfully!")
    else:
        print("Failed to send email.")


if __name__ == "__main__":
    main()
